#theme: jekyll-theme-minimal
# theme: jekyll-theme-slate
theme: jekyll-theme-minima
#theme: jekyll-theme-architect
logo: ./images/bavatar.png
title: INVOXES Blog
description: Hello, I'm Kousha (@INVOXES), a PenTester and Independent Security Researcher. I enjoy dissecting complex systems to understand how they work. Welcome to my blog! :)
